# Generated by Django 4.1.1 on 2022-10-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
